<?php

namespace Element\config;

$GLOBALS['USER_ID'] = 'USER_ID';
$GLOBALS['TASK_ID'] = 'TASK_ID';
$GLOBALS['TASK_TITLE'] = 'TASK_TITLE';
$GLOBALS['TASK_DATE'] = 'TASK_DATE';
$GLOBALS['DATE_DUE'] = 'DATE_DUE';
$GLOBALS['TASK_TYPE'] = 'TASK_TYPE';
$GLOBALS['REFERENCE'] = 'REFERENCE';
$GLOBALS['PERC_COMPLETE'] = 'PERC_COMPLETE';
$GLOBALS['DATE_COMPLTED'] = 'DATE_COMPLTED';
$GLOBALS['TASK_DESC'] = 'TASK_DESC';
$GLOBALS['TASK_NOTES'] = 'TASK_NOTES';
$GLOBALS['TASK_STATUS'] = 'TASK_STATUS';
$GLOBALS['UPDATE_DATE'] = 'UPDATE_DATE';
$GLOBALS['ASCENDING'] = 'ASCENDING';
$GLOBALS['DESCENDING'] = 'DESCENDING';
$GLOBALS['NOTE_ID'] = 'NOTE_ID';
$GLOBALS['NOTE_TITLE'] = 'NOTE_TITLE';
$GLOBALS['NOTE_DATE'] = 'NOTE_DATE';
$GLOBALS['NOTE_TEXT'] = 'NOTE_TEXT';
$GLOBALS['USER_ID'] = 'USER_ID';
$GLOBALS['USERNAME'] = 'USERNAME';
$GLOBALS['PASSWORD'] = 'PASSWORD';
$GLOBALS['USER_EMAIL'] = 'USER_EMAIL';
$GLOBALS['DATE_CREATED'] = 'DATE_CREATED';

$GLOBALS['DEFAULT_COMPARISON'] = '';
$GLOBALS['STRING_COMPARISON'] = 'strcmp';
$GLOBALS['INTEGER_COMPARISON'] = 'intcmp';
$GLOBALS['NUMERIC_COMPARISON'] = 'numcmp';

